### ISSUE TITLE
Error En el login 

### ISSUE THREAD

**Issue by cobymotion** [BloodCoding/Desing-SI#1]
No detecta los usuarios

**Comment by cobymotion** [comment]
No tiene seguridad con los usuarios

**Comment by cobymotion** [comment]
No presentaron avance

**Comment by FrankLamas** [comment]
Me falla todo cobi :'c dame chanza lo resolveré

**Comment by FrankLamas** [comment]
Cobiii recuperé mi avance dame chance :c

**Comment by cobymotion** [comment]
Ya se reparo el error
